name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.Pankajt07 }} -p ${{ secrets.Pank1234@# }} ${{ secrets.https://hub.docker.com/repository/docker/pankajt07/wisecow/general }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.Pankajt07 }}/wisecow:latest .
          docker push ${{ secrets.https://hub.docker.com/repository/docker/pankajt07/wisecow/general }}/wisecow:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to Kubernetes
        uses: aws/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          namespace: default
          manifest-file: kubernetes/deployment.yaml
